### ISSUE TITLE
pypi access rights

### ISSUE THREAD

**Issue by sureshvv** [rchrd2/django-google-cloud-storage#3]
Can you make me as maintainer on pypi? I have a new version.

**Comment by rchrd2** [comment]
What is your new version? Can you please explain what you changed and why? Is it backwards compatible with the old version? For example if users were to upgrade, would their old code still work?

**Comment by sureshvv** [comment]
> What is your new version?

```
             Version # TBD
```

> Can you please explain what you changed and why?

```
             Dependency on google-cloud package that is simpler and deals with authentication in a much easier way
```

> Is it backwards compatible with the old version? For example if users were to upgrade, would their old code still work?

```
             Yes. It will install google-cloud as part of the dependencies but the rest should be transparent.
```

**Comment by sureshvv** [comment]
Decided to release it as another package django-googlecloud-storage. Check if it works for you too,
